apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: service-registry
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: service-registry
    app.kubernetes.io/part-of: service-registry
  name: service-registry
  namespace: jduimovich
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: service-registry
    weight: 100
status: {}
